SELECT *
  FROM CUSTOMER;





SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_EXECUTION`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_EXECUTION_CONTEXT`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_EXECUTION_PARAMS`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_EXECUTION_SEQ`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_INSTANCE`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_JOB_SEQ`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_STEP_EXECUTION`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_STEP_EXECUTION_CONTEXT`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `BATCH_STEP_EXECUTION_SEQ`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `CUSTOMER`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;



---------------------------------
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE testDB.BATCH_JOB_EXECUTION;
TRUNCATE testDB.BATCH_JOB_EXECUTION_CONTEXT;
TRUNCATE testDB.BATCH_JOB_EXECUTION_PARAMS;
TRUNCATE testDB.BATCH_JOB_EXECUTION_SEQ;
TRUNCATE testDB.BATCH_JOB_INSTANCE;
TRUNCATE testDB.BATCH_JOB_SEQ;
TRUNCATE testDB.BATCH_STEP_EXECUTION;
TRUNCATE testDB.BATCH_STEP_EXECUTION_CONTEXT;
TRUNCATE testDB.BATCH_STEP_EXECUTION_SEQ;
TRUNCATE testDB.CUSTOMER;

SET FOREIGN_KEY_CHECKS = 1;
----------------------------------